theme: jekyll-theme-minimal
title: Tyler A. Scott
description: Associate Professor at UC Davis
logo: https://media-exp1.licdn.com/dms/image/C4E03AQFgruWzhpTOLQ/profile-displayphoto-shrink_400_400/0/1643652098575?e=1657152000&v=beta&t=ohuC8dNYdSFD3rQK1NfNPr9jBWr5y7iaYaYU0DRLmIs
show_downloads: false
